---
swagger: "2.0"
info:
  description: "Data provider for IoT data logging"
  version: "1.0.2"
  title: "Tinf IoT-Project"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/api"
schemes:
- "https"
paths:
  /machine:
    get:
      summary: "Get Service and Uptime"
      description: "Return the date of last service and the uptime of the machine"
      operationId: "getMachine"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Machine"
      x-swagger-router-controller: "Default"
  /sensor:
    get:
      summary: "Get all sensors"
      operationId: "getSensor"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Sensor"
        "400":
          description: "Invalid status value"
      x-swagger-router-controller: "Default"
    post:
      summary: "Adds a new sensor"
      description: ""
      operationId: "addSensor"
      consumes:
      - "application.json"
      parameters:
      - in: "body"
        name: "body"
        description: "Sensor object that need to be added"
        required: true
        schema:
          $ref: "#/definitions/Sensor"
      responses:
        "405":
          description: "invalid input"
      x-swagger-router-controller: "Default"
    put:
      summary: "Updates an existing sensor"
      description: ""
      operationId: "updateSensor"
      consumes:
      - "application.json"
      produces:
      - "application.json"
      parameters:
      - in: "body"
        name: "body"
        description: "Sensor object that need to be updated"
        required: true
        schema:
          $ref: "#/definitions/Sensor"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Sensor not found"
      x-swagger-router-controller: "Default"
  /sensor/{sensorId}:
    get:
      summary: "Get current value from a sensor"
      operationId: "getSensorById"
      produces:
      - "application/json"
      parameters:
      - name: "sensorId"
        in: "path"
        description: "ID of sensor"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/SensorData"
        "404":
          description: "Sensor not found"
      x-swagger-router-controller: "Default"
    delete:
      summary: "Deletes a sensor by Id"
      description: ""
      operationId: "deleteSensor"
      produces:
      - "application.json"
      parameters:
      - name: "sensorId"
        in: "path"
        description: "Sensor id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Sensor not found"
      x-swagger-router-controller: "Default"
  /sensor/{sensorId}/history:
    get:
      summary: "Get value history for single sensor"
      description: "Returns history for single sensor"
      operationId: "getSensorHistoryById"
      produces:
      - "application/json"
      parameters:
      - name: "sensorId"
        in: "path"
        description: "ID of sensor"
        required: true
        type: "integer"
        format: "int64"
      - name: "from"
        in: "query"
        description: "From timestamp"
        required: false
        type: "string"
        format: "DD-MM-YYYY HH:mm"
      - name: "to"
        in: "query"
        description: "To timestamp"
        required: false
        type: "string"
        format: "DD-MM-YYYY HH:mm"
      - name: "since"
        in: "query"
        description: "Since number of hours. Only evaluated if neither 'from' nor\
          \ 'to' supplied."
        required: false
        type: "number"
        default: 3.0
        format: "int"
      - name: "quantizeTo"
        in: "query"
        description: "Quantize to max. number of values. If less values measured,\
          \ also less values will be returned, i.e. no server-size interpolation."
        required: false
        type: "number"
        default: 100.0
        maximum: 300
        minimum: 10
        format: "int"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/SensorDataHistory"
        "404":
          description: "Sensor not found"
      x-swagger-router-controller: "Default"
definitions:
  Machine:
    type: "object"
    properties:
      lastservice:
        type: "string"
        format: "date"
      uptime:
        type: "string"
        format: "time"
    example:
      lastservice: "2000-01-23"
      uptime: "uptime"
  Sensor:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      sensorId:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      installationDate:
        type: "string"
        format: "date-time"
    example:
      name: "name"
      installationDate: "2000-01-23T04:56:07.000+00:00"
      id: 0
      sensorId: 6
  SensorData:
    type: "object"
    properties:
      sensorId:
        type: "integer"
        format: "int64"
      value:
        type: "number"
        format: "double"
      type:
        type: "integer"
        format: "int64"
      date:
        type: "string"
        format: "date-time"
    example:
      date: "2000-01-23T04:56:07.000+00:00"
      type: 1
      value: 6.027456183070403
      sensorId: 0
  SensorDataHistory:
    type: "object"
    properties:
      unitOfMeasure:
        type: "string"
      values:
        type: "array"
        items:
          $ref: "#/definitions/SensorDataHistory_values"
    example:
      unitOfMeasure: "unitOfMeasure"
      values:
      - date: "2000-01-23T04:56:07.000+00:00"
        value: 0.8008281904610115
      - date: "2000-01-23T04:56:07.000+00:00"
        value: 0.8008281904610115
  SensorDataHistory_values:
    type: "object"
    properties:
      date:
        type: "string"
        format: "date-time"
      value:
        type: "number"
        format: "double"
    example:
      date: "2000-01-23T04:56:07.000+00:00"
      value: 0.8008281904610115
