/**
 * Tinf IoT-Project
 * Data provider for IoT data logging
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SensorData { 
    sensorId?: number;
    value?: number;
    type?: number;
    date?: Date;
}
